# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'patient_reception' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
  pod 'MaterialComponents'
  pod 'SVProgressHUD'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'ZXingObjC', '~> 3.2.2'
  pod 'Alamofire', '~> 4.7'
  pod 'Alamofire-SwiftyJSON', '~> 3.0.0'
  pod 'SwiftyJSON', '~> 4.0'
  
  # Pods for patient_reception

end
